n = input('Digite algo: ')
print(type(n))
print('Alfabeto: ',n.isalpha())
print('Número',n.isnumeric())
print('Minusculo',n.islower())
print('Maiusculo',n.isupper())
print('Alfa-numérico',n.isalnum())
print('imprimivel ', n.isprintable())
print('identificador ', n.isidentifier())
print('', n.isascii())
print('capitalizada', n.istitle())
print('apenas espaços: ', n.isspace())